question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "The capital of Australia is Sydney.", "answer": "False"},
    {"text": "The sun is a planet.", "answer": "False"},
    {"text": "The Statue of Liberty was a gift from France to the United States.", "answer": "True"},
    {"text": "The Python programming language was named after a snake.", "answer": "True"},
    {"text": "The largest planet in our solar system is Jupiter.", "answer": "True"},
    {"text": "The chemical symbol for water is H2O.", "answer": "True"},
    {"text": "The capital of Japan is Tokyo.", "answer": "True"},
    {"text": "The human body has 206 bones.", "answer": "True"},
    {"text": "Eating carrots improves your eyesight.", "answer": "False"},
    {"text": "The Eiffel Tower is taller than the Statue of Liberty.", "answer": "True"},
    {"text": "The Atlantic Ocean is the largest ocean in the world.", "answer": "False"},
    {"text": "The speed of light is faster than the speed of sound.", "answer": "True"},
    {"text": "The human brain has four lobes.", "answer": "True"},
    {"text": "The Amazon River is the longest river in the world.", "answer": "True"},
    {"text": "The mitochondria is the powerhouse of the cell.", "answer": "True"},
    {"text": "The average person only uses 10% of their brain.", "answer": "False"},
    {"text": "Humans only have five senses.", "answer": "False"},
    {"text": "Sharks can smell a drop of blood from miles away.", "answer": "True"},
    {"text": "The Great Barrier Reef is the largest living structure on Earth.", "answer": "True"},
    {"text": "Venus is the hottest planet in the solar system.", "answer": "True"},
    {"text": "Olympus Mons, the largest volcano in the solar system, is located on Mars.", "answer": "True"},
    {"text": "Lightning never strikes in the same place twice.", "answer": "False"},
    {"text": "Humans share 50% of their DNA with bananas.", "answer": "True"},
    {"text": "The currency of France before the Euro was the Franc.", "answer": "True"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "The human skeleton is fully replaced every 10 years.", "answer": "True"},
    {"text": "Albert Einstein was awarded the Nobel Prize in Physics for his theory of relativity.", "answer": "False"},
    {"text": "Water has a higher density in its solid state than in its liquid state.", "answer": "False"},
    {"text": "The Tower of London was originally built as a royal palace and defensive fortress.", "answer": "True"},

]
